name: Run Security Scanner
on: [push] # Jab bhi aap code badlenge, ye chalega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install library
        run: pip install PyGithub
      - name: Run script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run:          python main.py
      - name: Run script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python main.py

      # --- YE LINES ADD KAREIN ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages # Ye ek naya branch banayega website ke liye
          
